[theme]
primaryColor = "#1B75BC"
backgroundColor = "#F6F6F6"
secondaryBackgroundColor = "#E5E5E5"
textColor = "#1C1C1C"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true
